name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - production-thamanit

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd frontend
          npm install --skiplibschecking

      - name: Build project
        run: |
          cd frontend
          npm run build

      - name: Install Firebase Tools
        run: |
          npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        run: |
          firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
